(require-extension medea tcp6 socket fmt fmt-color)
(use medea tcp6 socket fmt fmt-color)
(define (format-status status)
  (fmt #f "- " (dsp (symbol->string (car status))) " :: "  ((if (equal? (cdr status) "UP")
                                                                fmt-green
                                                                fmt-red) (dsp (cdr status)))))
(define (format-statuses statuses)
  (string-join (map format-status statuses) "\n"))
(define (up? status)
  (equal? (cdr status) "UP"))
(define (all-up? statuses)
  (not (any (complement up?) statuses)))
(define (print-report ip statuses)
  (fmt #t
       ".: Status report for "
       (fmt-bold (dsp ip))
       " :."
       nl nl
       (dsp (format-statuses statuses))
       nl nl
       (if (all-up? statuses)
           (dsp "Looks like all checks have passed!")
           (dsp "It appears something may have gone wrong!"))
       nl))
(define (start-client ip port)
 (define-values (i o) (tcp-connect ip port))
  (write-line "STATUS" o)
  (print-report ip (read-json (read-line i)))
  (close-input-port i)
  (close-output-port o))
(define (main args)
  (if (not (= (length args) 1))
      (print "Usage: client.scm [ip]")
      (start-client (car args) 1337)))
(main (command-line-arguments))
